import openai
from openai import OpenAI  # OpenAI --create a client object to communicate with OpenAI's API in the newer SDK
import os
import json
from dotenv import load_dotenv

# Load .env and API key
load_dotenv("env")
api_key = os.getenv("OPENAI_API_KEY")

# Initialize OpenAI client (✅ REQUIRED in new SDK)
client = OpenAI(api_key=api_key)

def chat_with_ai(user_input):
    """
    Sends user input to the OpenAI chat model and retrieves the assistant's response.

    Args:
        user_input (str): The message entered by the user.

    Returns:
        str: The assistant's response generated by the language model.
    """
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "user", "content": user_input},
        ],
        temperature=1.0,
        max_tokens=100
    )
    return response.choices[0].message.content

# Start a loop to keep chatting
print("Hi! I’m your virtual assistant. Ask me anything!")
print("Type 'bye' or 'exit' to end the chat.")

while True:
    user_input = input("You: ")

    if user_input.lower() == "exit" or user_input.lower() == "bye":
        print("Take care! Your assistant is signing off.")
        break

    ai_reply = chat_with_ai(user_input)
    print("AI:", ai_reply)
